// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEVuY1IFSxyqPbi3OvHoiX2mnqFQbIFuE',
    appId: '1:363779680764:web:a294fce103396a1eb8ea79',
    messagingSenderId: '363779680764',
    projectId: 'catalogo-peliculas-31c2f',
    authDomain: 'catalogo-peliculas-31c2f.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-31c2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVenYtdw2c_eCxEC6WSGM4KDR39NHej2E',
    appId: '1:363779680764:android:6f1bc1b99dc694c3b8ea79',
    messagingSenderId: '363779680764',
    projectId: 'catalogo-peliculas-31c2f',
    storageBucket: 'catalogo-peliculas-31c2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA10qe3EBWy4yv5V-5_ZKezykRo5NX_xq4',
    appId: '1:363779680764:ios:6cdbcb75e44baefab8ea79',
    messagingSenderId: '363779680764',
    projectId: 'catalogo-peliculas-31c2f',
    storageBucket: 'catalogo-peliculas-31c2f.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA10qe3EBWy4yv5V-5_ZKezykRo5NX_xq4',
    appId: '1:363779680764:ios:6cdbcb75e44baefab8ea79',
    messagingSenderId: '363779680764',
    projectId: 'catalogo-peliculas-31c2f',
    storageBucket: 'catalogo-peliculas-31c2f.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEVuY1IFSxyqPbi3OvHoiX2mnqFQbIFuE',
    appId: '1:363779680764:web:1bcdb79c78384c59b8ea79',
    messagingSenderId: '363779680764',
    projectId: 'catalogo-peliculas-31c2f',
    authDomain: 'catalogo-peliculas-31c2f.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-31c2f.firebasestorage.app',
  );
}
